# =========================
# Kitty Terminal Config
# =========================

# Dynamic Matugen colors
allow_remote_control yes


include matugen.conf

# =========================
# Fonts
# =========================

font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

# =========================
# Window
# =========================

window_padding_width 12

# Transparency
background_opacity 0.82
dynamic_background_opacity yes

# Blur
background_blur 1

# Hide titlebar
hide_window_decorations yes

# =========================
# Cursor
# =========================

cursor_shape beam
cursor_blink_interval 0.5

# =========================
# Scrollback
# =========================

scrollback_lines 10000

# =========================
# Bell
# =========================

enable_audio_bell no

# =========================
# Tabs
# =========================

tab_bar_style powerline
tab_bar_edge top

# =========================
# Performance
# =========================

repaint_delay 10
input_delay 3
sync_to_monitor yes

# =========================
# URL Styling
# =========================

url_style curly