foreground              #dde3ee
background              #0e141c

selection_foreground    #00325a
selection_background    #a1c9ff

cursor                  #a1c9ff
cursor_text_color       #0e141c

url_color               #c2c1f9

active_border_color     #a1c9ff
inactive_border_color   #0e141c

# Black
color0  #0e141c
color8  #343a43

# Red
color1  #ffb4ab
color9  #93000a

# Green
color2  #bbc6ea
color10 #3b4665

# Yellow
color3  #c2c1f9
color11 #424271

# Blue
color4  #a1c9ff
color12 #004880

# Magenta
color5  #0060a8
color13 #dde3ee

# Cyan
color6  #c2c1f9
color14 #424271

# White
color7  #dde3ee
color15 #c1c7d2